package com.project.webfitnesstracker.model;

public enum WorkoutType {
    RUNNING,CYCLING,SWIMMING,YOGA,DANCE,
    HIKING,STRENGTH_TRAINING,AEROBICS,
    PILATES,CIRCUIT_TRAINING,POWER_WALKING,
    SKIPPING_ROPE,WALKING,BODYBUILDING,
    ECCENTRIC_TRAINING,FUNCTIONAL_TRAINING,
    SPRINTING,WEIGHT_TRAINING,CALISTHENICS,
    STRETCHING,OTHER
}
