server:
  port: 8080

spring:
  profiles.default: postgres
  sql.init.mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      jdbc:
        lob:
          non_contextual_creation: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.webfitnesstracker: INFO
  file:
      name: logs/fitness-tracker.log
